### PR TITLE
Add support for data type and initial tests

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by aasatt** [comment]
Is `init(_ data:)` ever used?

**Comment by 3lvis** [comment]
@aasatt was supossed to be used when initializing a `JSONResult`.

**Comment by aasatt** [comment]
I don't agree with this part: 

```
if let dictionary = body as? [String: Any] {
     json = JSON(dictionary)
 } else if let array = body as? [[String: Any]] {
     json = JSON(array)
  } else if let data = body as? Data {
     json = JSON(data)
 } else {
     json = JSON.none
 }
```

At least it's incomplete since it will never be initialized with a `Data` body. 

`func handleJSONRequest(...)` will always deserialize JSON data  and `func requestJSON` will always initialize `JSONResult` with that deserialized body.

**Comment by 3lvis** [comment]
@aasatt Hi! That was a brainfart, I think this is what you wanted: https://github.com/3lvis/Networking/pull/213

**Pull request merged**
