### PR TITLE
Fix build issue for target platform iOS

### PR DESCRIPTION
**Pull request by mrylmz**

### CODE REVIEW

**Comment by 3lvis** [comment]
Hi @mrylmz,

Which Swift version are you using?

**Comment by mrylmz** [comment]
```
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.6.0
```

**Comment by mrylmz** [comment]
I'm not sure why that is an error message and not a warning but Xcode isn't able to build for iOS without the renaming.

**Comment by 3lvis** [comment]
I'll double check

**Comment by Arestronaut** [comment]
Bump on this one. I still get the same issue using the following swift version:
```
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin19.4.0
```

**Comment by 3lvis** [comment]
I believe this should be fixed now

**Pull request closed without merging**
