### PR TITLE
Added basic data downloading method

### PR DESCRIPTION
**Pull request by Elland**
- Gets the job done for now.

### CODE REVIEW

**Comment by 3lvis** [comment]
I have a proposal for the downloadData method.

```swift
/**
 Downloads data from a URL, caching the result.
 - parameter path: The path used to download the resource
 - parameter completion: A closure that gets called when the download request is completed, it contains a `data` object and a `NSError`.
 */
public func downloadData(path: String, completion: (data: NSData?, error: NSError?) -> Void) {
    let url = self.urlForPath(path)
    var found = false
    self.session.getTasksWithCompletionHandler { dataTasks, uploadTasks, downloadTasks in
        for downloadTask in downloadTasks {
            if downloadTask.originalRequest?.URL?.absoluteString == url.absoluteString {
                found = true
            }
        }
    }

    if !found {
        self.session.dataTaskWithURL(url) { data, response, error in
            completion(data: data, error: error)
            }.resume()
    }
}
```

Would that work for you too?

**Comment by 3lvis** [comment]
I guess caching is missing there. 💭

**Comment by 3lvis** [comment]
Added caching:

```swift
public func downloadData(path: String, completion: (data: NSData?, error: NSError?) -> Void) {
    let url = self.urlForPath(path)
    if let cachedData = self.cache.objectForKey(url.absoluteString) as? NSData {
        dispatch_async(dispatch_get_main_queue()) {
            completion(data: cachedData, error: nil)
        }
    } else {
        var found = false
        self.session.getTasksWithCompletionHandler { dataTasks, uploadTasks, downloadTasks in
            for downloadTask in downloadTasks where downloadTask.originalRequest?.URL?.absoluteString == url.absoluteString {
                found = true
            }
        }

        if !found {
            self.session.dataTaskWithURL(url) { data, response, error in
                if let data = data {
                    self.cache.setObject(data, forKey: url.absoluteString)
                }
                completion(data: data, error: error)
                }.resume()
        }
    }
}
```

**Comment by Elland** [comment]
@3lvis  👍

**Pull request merged**
