### PR TITLE
Add flag to disable error logging

### PR DESCRIPTION
**Pull request by kientux**
In release build, usually we should disable logging to improve performance and hide sensitive information. In function `logError` I just check for flag `disableErrorLogging` and return if it's `true`.

 I don't know if there's a more efficient/convenient way to do this (maybe a `static var` instead of `var`?).

### CODE REVIEW

**Comment by kientux** [comment]
It seems that I messed up things with these commits :(

**Comment by 3lvis** [comment]
Sounds good!

**Comment by kientux** [comment]
Sorry... Could you please change it to `public var`? Or else we can't use it as embeded framework :( What a stupid mistake..

**Comment by 3lvis** [comment]
Done!

**Pull request merged**
